config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  devise_for :admins
  devise_for :users

  resources :users do
    resources :leads
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :leads
      end
    end
  end

  resources :admins
  resources :statuses
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :user
  has_many :statuses, dependent: :delete_all

  def current_step
    if statuses.any?
      statuses.find_by(active: true).name
    end
  end

  def progress_level
    if statuses.any?
      statuses.find_by(active: true).progress_level
    else
      return 0
    end
  end
end

app/controllers/api/v1/leads_controller.rb
class Api::V1::LeadsController < ApplicationController
  before_action :authenticate_authorized_user
  
  def index
    @leads = Lead.where(user_id: params[:user_id]).sort_by(&:progress_level).reverse
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :authenticate_authorized_user
  before_action :set_user

  def index
    gon.user_id = params[:user_id]
  end

  def show
    @lead = Lead.find(params[:id])
    last_active_status = Status.where("lead_id = ? AND active = ?", @lead.id, true)
  end

  def new
  end

  def create
    datetime = params[:lead]["date(1i)"] + "-" + params[:lead]["date(2i)"] + "-" + params[:lead]["date(3i)"] + " " + params[:lead]["date(4i)"] + ":" + params[:lead]["date(5i)"]
    @lead = Lead.new(
    # change user_id when Devise is installed
      user_id: @user.id,
      name: params[:name],
      job_title: params[:job_title],
      company: params[:company],
      email: params[:email],
      phone: params[:phone],
      notes: params[:notes],
      last_action: datetime
    )
    if @lead.save
      status = Status.new(
        lead_id: @lead.id,
        name: "Sent Invite on LinkedIn",
        date: datetime
      )
      if status.save
        flash[:success] = "Lead was successfully saved."
        redirect_to user_lead_path(@user, @lead)
      else
        @lead.destroy
        flash[:danger] = "There was an error while saving your lead. Please try again."
        render :new
      end
    else
      render :new
    end
  end

  def edit
    @lead = Lead.find(params[:id])
  end

  def update
    @lead = Lead.find(params[:id])
    if @lead.update(
    # change user_id when Devise is installed
      user_id: 1,
      name: params[:name],
      job_title: params[:job_title],
      company: params[:company],
      email: params[:email],
      phone: params[:phone],
      notes: params[:notes]
    )
      flash[:success] = "Lead has been successfully updated."
      redirect_to user_lead_path(@user, @lead)
    else
      flash[:danger] = "There was an error while saving your lead. Please try again."
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])

    unless current_admin || current_user.id == @user.id
      flash[:warning] = "You are not authorized to view this page"
      redirect_to root_path
    end
  end
end

app/helpers/api/v1/leads_helper.rb
module Api::V1::LeadsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/edit.html.erb
<h1>Edit Lead</h1>
<%= form_tag user_lead_path(@user, @lead), method: :patch do %>
  <div>
    <%= label_tag :name %>
    <%= text_field_tag :name, @lead.name %>
  </div>
  <div>
    <%= label_tag :job_title %>
    <%= text_field_tag :job_title, @lead.job_title %>
  </div>
  <div>
    <%= label_tag :company %>
    <%= text_field_tag :company, @lead.company %>
  </div>
  <div>
    <%= label_tag :email %>
    <%= text_field_tag :email, @lead.email %>
  </div>
  <div>
    <%= label_tag :phone %>
    <%= text_field_tag :phone, @lead.phone %>
  </div>
  <div>
    <%= label_tag :notes %>
    <%= text_area_tag :notes, @lead.notes %>
  </div>
  <div>
    <%= submit_tag "Submit" %>
  </div>
<% end %>

app/views/leads/index.html.erb
<div id="leads-index">
  <h2>My Leads</h2>
  <input v-model="searchField">
  <table>
    <tr>
      <th @click="orderByField('name')">Name</th>
      <th @click="orderByField('company')">Company</th>
      <th @click="orderByField('job_title')">Job Title</th>
      <th @click="orderByField('email')">Email</th>
      <th @click="orderByField('phone')">Phone</th>
      <th @click="orderByField('notes')">notes</th>
      <th @click="orderCurrentStep()">Current Step</th>
    </tr>
    <tr v-for="lead in tableFilter">
      <td><a v-bind:href="urlBuilder(lead.id)">{{ lead.name }}</a></td>
      <td>{{ lead.company }}</td>
      <td>{{ lead.job_title }}</td>
      <td>{{ lead.email }}</td>
      <td>{{ lead.phone }}</td>
      <td>{{ lead.notes }}</td>
      <td>{{ lead.current_step }}</td>
    </tr>
  </table>
</div>

app/views/leads/new.html.erb
<h1>New Lead</h1>
<%= form_tag user_leads_path(@user), method: :post do %>
  <div>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
  </div>
  <div>
    <%= label_tag :job_title %>
    <%= text_field_tag :job_title %>
  </div>
  <div>
    <%= label_tag :company %>
    <%= text_field_tag :company %>
  </div>
  <div>
    <%= label_tag :email %>
    <%= text_field_tag :email %>
  </div>
  <div>
    <%= label_tag :phone %>
    <%= text_field_tag :phone %>
  </div>
  <div>
    <%= label_tag :date, "Contact initated on: " %><span title="Initial contact includes LinkedIn Invite Sent, introduction email, Meet-up, etc. Please specify form of contact in the notes."> ?</span>
    <%= datetime_select(:lead, :date, default: Time.zone.now) %>
  </div>
  <div>
    <%= label_tag :notes %>
    <%= text_area_tag :notes %>
  </div>
  <div>
    <%= submit_tag "Submit" %>
  </div>
<% end %>

app/views/leads/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="well">
      <dl class="dl-horizontal">
        <dt>Name: </dt>
        <dd><%= @lead.name %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Job Title: </dt>
        <dd><%= @lead.job_title %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Company: </dt>
        <dd><%= @lead.company %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Email: </dt>
        <dd><%= @lead.email %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Phone: </dt>
        <dd><%= @lead.phone %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Notes: </dt>
        <dd><%= @lead.notes%></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Last Updated: </dt>
        <dd><%= @lead.last_action.strftime("%b %e, %Y -- %l:%M%P")%></dd>
      </dl>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-2">
    <div class="status-panel-wrap">
      <div class="well">
        <%= link_to "", "#", data: {toggle: "modal", target: "#Connect-#{@lead.id}"} %>
        <h3>Connected on LinkedIn</h3>
      </div>
    </div>
  </div>
  <div class="col-md-2">
    <div class="status-panel-wrap">
      <div class="well">
        <%= link_to "", "#", data: {toggle: "modal", target: "#Email-#{@lead.id}"} %>
        <h3>Email Sent</h3>
      </div>
    </div>
  </div>
  <div class="col-md-2">
    <div class="status-panel-wrap">
      <div class="well">
        <%= link_to "", "#", data: {toggle: "modal", target: "#Meeting-#{@lead.id}"} %>
        <h3>Set Meeting</h3>
      </div>
    </div>
  </div>
  <div class="col-md-2">
    <div class="status-panel-wrap">
      <div class="well">
        <%= link_to "", "#", data: {toggle: "modal", target: "#Interview-#{@lead.id}"} %>
        <h3>Set Interview</h3>
      </div>
    </div>
  </div>
  <div class="col-md-2">
    <div class="status-panel-wrap">
      <div class="well">
        <%= link_to "", "#", data: {toggle: "modal", target: "#JobOffer-#{@lead.id}"} %>
        <h3>Job Offer</h3>
      </div>
    </div>
  </div>
  <div class="col-md-1"></div>
</div>


<div id="Connect-<%= @lead.id %>" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3>Connected On LinkedIn</h3>
      </div>
      <div class="modal-body">
        <%= form_tag '/statuses', method: :post do %>
          <div>
            <%= hidden_field_tag :name, "LinkedIn Invite Accepted" %>
            <%= hidden_field_tag :lead_id, @lead.id %>
          </div>
          <div class="form-group">
            <%= label_tag :notes %>
            <%= text_area_tag :notes %>
          </div>
          <div>
            <%= label_tag :date, "Date Invite Accepted" %>
            <%= datetime_select(:date, :date) %>
          </div>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
          <%= submit_tag "Submit", class: "btn btn-info"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="Email-<%= @lead.id %>" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3>Email Sent</h3>
      </div>
      <div class="modal-body">
        <%= form_tag '/statuses', method: :post do %>
          <div>
            <%= hidden_field_tag :name, "Sent Email" %>
            <%= hidden_field_tag :lead_id, @lead.id %>
          </div>
          <div>
            <%= label_tag :notes %>
            <%= text_area_tag :notes %>
          </div>
          <div>
            <%= label_tag :date, "Date Email Sent" %>
            <%= datetime_select(:date, :date) %>
          </div>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
          <%= submit_tag "Submit", class: "btn btn-info"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="Meeting-<%= @lead.id %>" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3>Set Meeting</h3>
      </div>
      <div class="modal-body">
        <%= form_tag '/statuses', method: :post do %>
          <div>
            <%= hidden_field_tag :name, "Set Meeting" %>
            <%= hidden_field_tag :lead_id, @lead.id %>
          </div>
          <div>
            <%= label_tag :notes %>
            <%= text_area_tag :notes %>
          </div>
          <div>
            <%= label_tag :date, "Date Meeting Set" %>
            <%= datetime_select(:date, :date) %>
          </div>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
          <%= submit_tag "Submit", class: "btn btn-info"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="Interview-<%= @lead.id %>" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3>Set Interview</h3>
      </div>
      <div class="modal-body">
        <%= form_tag '/statuses', method: :post do %>
          <div>
            <%= hidden_field_tag :name, "Interview Set" %>
            <%= hidden_field_tag :lead_id, @lead.id %>
          </div>
          <div>
            <%= label_tag :notes %>
            <%= text_area_tag :notes %>
          </div>
          <div>
            <%= label_tag :date, "Date Job Interview Set" %>
            <%= datetime_select(:date, :date) %>
          </div>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
          <%= submit_tag "Submit", class: "btn btn-info"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="JobOffer-<%= @lead.id %>" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3>Job Offer Made</h3>
      </div>
      <div class="modal-body">
        <%= form_tag '/statuses', method: :post do %>
          <div>
            <%= hidden_field_tag :name, "Job Offer" %>
            <%= hidden_field_tag :lead_id, @lead.id %>
          </div>
          <div>
            <%= label_tag :notes %>
            <%= text_area_tag :notes %>
          </div>
          <div>
            <%= label_tag :date, "Date Job Offer Made" %>
            <%= datetime_select(:date, :date) %>
          </div>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
          <%= submit_tag "Submit", class: "btn btn-info"%>
        <% end %>
      </div>
    </div>
  </div>
</div>